name: PR Lint 

on:
    pull_request:
        branches: [main]
    
jobs:
    pr-lint:
        name: Validate PR commit
        permissions: 
            pull-requests: write 
        runs-on: ubuntu-latest
        steps:
            - uses: amannn/action-semantic-pull-request@v4.5.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                requireScope: false