name: Release

on: 
    push:
        branches:
            ## NOTE: Update the branch to main if you want to release when new changes are merged to main
            - release 

jobs:
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps: 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          role-session-name: GITHUB_TO_AWS_via_FederatedODIC
          aws-region: ap-southeast-2
          audience: sts.amazonaws.com

      - name: Sts GetCallerIdentity
        run: | 
          aws sts get-caller-identity

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run deploy script 
        run: ./deploy.sh
        shell: bash
        env:
          S3_BUCKET_NAME: byd-lambda-zip 
          LAMBDA_HANDLER_NAME: byd-dev-restapi-lambda-handler